-- Course 5: Waste Management & Recycling (6 modules, 10 questions each)
INSERT INTO module_test_questions (course_id, module_id, question, options, correct_answer) VALUES
('5', 0, 'What is waste management?', '["Creating waste", "Collection, transport, and disposal of waste", "Littering", "Shopping"]', 1),
('5', 0, 'What is municipal solid waste?', '["Industrial waste", "Everyday trash from homes and businesses", "Medical waste", "Hazardous waste"]', 1),
('5', 0, 'What are the 3 Rs?', '["Run, Rest, Relax", "Reduce, Reuse, Recycle", "Read, Write, Review", "Red, Round, Real"]', 1),
('5', 0, 'What is the waste hierarchy?', '["Waste size", "Priority order for waste management", "Waste weight", "Trash can"]', 1),
('5', 0, 'What is the most preferred waste management option?', '["Landfill", "Waste prevention", "Incineration", "Recycling"]', 1),
('5', 0, 'What is a landfill?', '["Park", "Site for waste disposal by burial", "Recycling center", "Store"]', 1),
('5', 0, 'What is leachate?', '["Clean water", "Contaminated liquid from landfill", "Fertilizer", "Recycled material"]', 1),
('5', 0, 'What percentage of waste can typically be recycled?', '["0%", "50-75%", "100%", "5%"]', 1),
('5', 0, 'What is e-waste?', '["Email", "Discarded electronic devices", "Energy waste", "Food waste"]', 1),
('5', 0, 'Why is waste management important?', '["It is not", "Protects health and environment", "Creates jobs only", "No reason"]', 1),
('5', 1, 'What is recycling?', '["Making trash", "Converting waste into reusable material", "Burning waste", "Burying waste"]', 1),
('5', 1, 'What materials are commonly recyclable?', '["Only plastic", "Paper, glass, metal, and some plastics", "Food waste", "Diapers"]', 1),
('5', 1, 'What is single-stream recycling?', '["One item only", "All recyclables mixed in one bin", "Separate sorting", "No recycling"]', 1),
('5', 1, 'What is contamination in recycling?', '["Clean materials", "Non-recyclables mixed with recyclables", "Sorted waste", "New items"]', 1),
('5', 1, 'Can pizza boxes be recycled?', '["Always", "Only if not greasy", "Never", "After washing"]', 1),
('5', 1, 'What is downcycling?', '["Upgrading", "Recycling into lower-quality material", "Not recycling", "Composting"]', 1),
('5', 1, 'What is closed-loop recycling?', '["Throwing away", "Material recycled into same product repeatedly", "One-time recycle", "No recycling"]', 1),
('5', 1, 'What plastic number is most recyclable?', '["All equally", "#1 (PET) and #2 (HDPE)", "#7", "None"]', 1),
('5', 1, 'Should you rinse recyclables?', '["Never", "Yes, to prevent contamination", "Only sometimes", "Use soap"]', 1),
('5', 1, 'What is wishcycling?', '["Good practice", "Putting non-recyclables in recycling hoping they are", "Donating", "Composting"]', 1),
('5', 2, 'What is composting?', '["Burning", "Decomposing organic waste into soil amendment", "Recycling plastic", "Landfilling"]', 1),
('5', 2, 'What can be composted?', '["Plastic bags", "Fruit scraps, vegetables, and yard waste", "Metal cans", "Glass"]', 1),
('5', 2, 'What cannot be composted?', '["Leaves", "Meat, dairy, and pet waste", "Vegetable peels", "Coffee grounds"]', 1),
('5', 2, 'What is green material in composting?', '["Green colored items", "Nitrogen-rich materials like food scraps", "Plastic", "Glass"]', 1),
('5', 2, 'What is brown material in composting?', '["Brown colored items", "Carbon-rich materials like leaves", "Dirt", "Rocks"]', 1),
('5', 2, 'What is the ideal green-to-brown ratio?', '["All green", "About 1:2 or 1:3", "All brown", "Equal parts"]', 1),
('5', 2, 'What conditions speed up composting?', '["Cold and dry", "Warm, moist, and aerated", "Frozen", "No oxygen"]', 1),
('5', 2, 'How long does composting take?', '["One day", "2-12 months depending on method", "One week", "Years"]', 1),
('5', 2, 'What is vermicomposting?', '["Hot composting", "Using worms to break down waste", "Chemical process", "Burning"]', 1),
('5', 2, 'What is the benefit of compost?', '["None", "Enriches soil and reduces landfill waste", "Smells bad", "Creates waste"]', 1),
('5', 3, 'What is hazardous waste?', '["Normal trash", "Waste that poses danger to health or environment", "Paper", "Food waste"]', 1),
('5', 3, 'What are examples of household hazardous waste?', '["Newspaper", "Paint, batteries, and cleaning chemicals", "Cardboard", "Food scraps"]', 1),
('5', 3, 'How should batteries be disposed of?', '["Regular trash", "At designated collection points", "Burn them", "In recycling bin"]', 1),
('5', 3, 'What is e-waste?', '["Email", "Electronic waste like old phones and computers", "Energy waste", "Food waste"]', 1),
('5', 3, 'Why is e-waste dangerous?', '["It is not", "Contains toxic materials like lead and mercury", "Too heavy", "Takes space"]', 1),
('5', 3, 'How should paint be disposed of?', '["Pour down drain", "Dry out or take to hazardous waste facility", "Regular trash", "Burn it"]', 1),
('5', 3, 'What is the symbol for hazardous waste?', '["Smiley face", "Skull and crossbones or warning triangle", "Heart", "Star"]', 1),
('5', 3, 'Can fluorescent bulbs go in regular trash?', '["Yes", "No, they contain mercury", "Sometimes", "After breaking"]', 1),
('5', 3, 'What is a household hazardous waste collection event?', '["Party", "Event where residents can safely dispose of hazardous items", "Sale", "Festival"]', 1),
('5', 3, 'Why read product labels?', '["Not necessary", "To find disposal instructions", "For fun", "To check price"]', 1),
('5', 4, 'What is source reduction?', '["Recycling", "Reducing waste at the point of creation", "Burning", "Burying"]', 1),
('5', 4, 'What is a reusable alternative to plastic bags?', '["More plastic bags", "Cloth or canvas bags", "Paper plates", "Styrofoam"]', 1),
('5', 4, 'What is zero waste?', '["Recycling only", "Lifestyle aimed at sending nothing to landfill", "Creating waste", "Burning everything"]', 1),
('5', 4, 'How can you reduce food waste?', '["Buy more", "Plan meals and store food properly", "Throw away more", "Never shop"]', 1),
('5', 4, 'What is planned obsolescence?', '["Long-lasting products", "Designing products to fail or become outdated", "Quality manufacturing", "Repairable items"]', 1),
('5', 4, 'What is buying in bulk beneficial?', '["More expensive", "Reduces packaging waste", "Creates waste", "Harder to store"]', 1),
('5', 4, 'What is upcycling?', '["Throwing away", "Creating higher-value products from waste", "Burning", "Burying"]', 1),
('5', 4, 'What is a circular economy?', '["Linear consumption", "System that eliminates waste through reuse", "One-time use", "Wasteful economy"]', 1),
('5', 4, 'What is minimalism?', '["Hoarding", "Lifestyle of owning fewer possessions", "Shopping more", "Wasting"]', 1),
('5', 4, 'What is the best way to reduce waste?', '["Recycle everything", "Not create it in the first place", "Burn it", "Hide it"]', 1),
('5', 5, 'What is industrial waste?', '["Home trash", "Waste from manufacturing and industry", "Food waste", "Paper"]', 1),
('5', 5, 'What is construction and demolition waste?', '["Office paper", "Debris from building projects", "Food", "Electronics"]', 1),
('5', 5, 'What percentage of C&D waste can be recycled?', '["0%", "Up to 70-90%", "5%", "100%"]', 1),
('5', 5, 'What is an environmental management system?', '["Trash can", "Framework for managing environmental responsibilities", "Recycling bin", "Landfill"]', 1),
('5', 5, 'What is waste auditing?', '["Guessing", "Analyzing waste streams to identify reduction opportunities", "Throwing away", "Ignoring"]', 1),
('5', 5, 'What is extended producer responsibility?', '["Consumer duty", "Manufacturers responsible for end-of-life product management", "Government role", "No responsibility"]', 1),
('5', 5, 'What is industrial symbiosis?', '["Competition", "One industry using another waste as resource", "Isolation", "No cooperation"]', 1),
('5', 5, 'What is the cradle-to-cradle concept?', '["Linear use", "Designing products for continuous reuse", "One-time use", "Disposal focus"]', 1),
('5', 5, 'What is life-cycle assessment?', '["Age check", "Analyzing environmental impact from production to disposal", "Price evaluation", "Color analysis"]', 1),
('5', 5, 'Why is waste-to-energy controversial?', '["It is not", "May discourage recycling and create emissions", "Too efficient", "Free energy"]', 1);