-- Course 4: Renewable Energy Basics (6 modules, 10 questions each)
-- Course 5: Waste Management (6 modules, 10 questions each)
-- Course 6: Energy Efficiency Auditing (6 modules, 10 questions each)
INSERT INTO module_test_questions (course_id, module_id, question, options, correct_answer) VALUES
-- Course 4 questions (continuing in next migration due to size limit)
('4', 0, 'What is renewable energy?', '["Fossil fuels", "Energy from sources that naturally replenish", "Nuclear power", "Coal"]', 1),
('4', 0, 'Which of these is NOT a renewable energy source?', '["Solar", "Natural gas", "Wind", "Hydro"]', 1),
('4', 0, 'What is the main benefit of renewable energy?', '["More expensive", "Reduces carbon emissions", "Depletes resources", "No benefits"]', 1),
('4', 0, 'What percentage of global energy comes from renewables?', '["Less than 1%", "About 30%", "100%", "5%"]', 1),
('4', 0, 'What is the fastest-growing renewable energy source?', '["Coal", "Solar power", "Oil", "Gas"]', 1),
('4', 0, 'What is energy transition?', '["Electricity switch", "Shift from fossil fuels to renewable energy", "Energy loss", "Power outage"]', 1),
('4', 0, 'What is the greenhouse effect?', '["Plant growth", "Warming caused by trapped atmospheric gases", "Green energy", "Garden feature"]', 1),
('4', 0, 'What is carbon neutrality?', '["Using carbon", "Balancing carbon emissions with removal", "No carbon", "More emissions"]', 1),
('4', 0, 'What is the Paris Agreement?', '["Travel document", "International climate accord", "Energy bill", "City plan"]', 1),
('4', 0, 'Why diversify energy sources?', '["More expensive", "Increases reliability and resilience", "Complicates things", "No reason"]', 1),
('4', 1, 'What is solar energy?', '["Moon energy", "Energy from the sun", "Wind energy", "Water energy"]', 1),
('4', 1, 'What are the two main solar technologies?', '["Hot and cold", "Photovoltaic (PV) and solar thermal", "Big and small", "Old and new"]', 1),
('4', 1, 'What does photovoltaic mean?', '["Light camera", "Light producing electricity", "Heat generation", "Wind power"]', 1),
('4', 1, 'What is solar thermal energy?', '["Cold energy", "Using sun heat for heating", "Electricity only", "Wind energy"]', 1),
('4', 1, 'What is a solar farm?', '["Vegetable farm", "Large-scale solar power plant", "Animal farm", "Small garden"]', 1),
('4', 1, 'What limits solar power generation?', '["Nothing", "Weather, time of day, and location", "Technology", "Cost only"]', 1),
('4', 1, 'What is solar panel efficiency?', '["Size", "Percentage of sunlight converted to electricity", "Color", "Weight"]', 1),
('4', 1, 'Where is solar power most effective?', '["Polar regions", "Sunny, low-latitude areas", "Underground", "At night"]', 1),
('4', 1, 'What is concentrated solar power?', '["Tiny panels", "Using mirrors to concentrate sunlight for power", "Regular panels", "Batteries"]', 1),
('4', 1, 'Can solar work at night?', '["Always", "Only with battery storage", "Yes normally", "Better at night"]', 1),
('4', 2, 'What is wind energy?', '["Solar power", "Power generated from wind movement", "Water power", "Fire power"]', 1),
('4', 2, 'What is a wind turbine?', '["Solar panel", "Device that converts wind to electricity", "Water wheel", "Engine"]', 1),
('4', 2, 'Where are wind farms typically located?', '["Cities", "Windy areas like coasts and plains", "Forests", "Underground"]', 1),
('4', 2, 'What is offshore wind energy?', '["Beach power", "Wind turbines installed in ocean", "Land turbines", "Underground wind"]', 1),
('4', 2, 'What is the capacity factor of wind?', '["100%", "Percentage of time turbine produces power", "Turbine size", "Wind speed"]', 1),
('4', 2, 'What are the main parts of a wind turbine?', '["Just blades", "Rotor, nacelle, and tower", "Engine", "Battery"]', 1),
('4', 2, 'What minimum wind speed is needed?', '["Any speed", "About 6-9 mph (10-15 km/h)", "100 mph", "No wind needed"]', 1),
('4', 2, 'What is the advantage of offshore wind?', '["Cheaper", "Stronger and more consistent winds", "Easier access", "Less power"]', 1),
('4', 2, 'What is wind power intermittency?', '["Constant power", "Variable power due to changing wind", "No power", "High power always"]', 1),
('4', 2, 'How do wind turbines face the wind?', '["They do not", "Yaw mechanism adjusts direction", "Fixed position", "Manual adjustment"]', 1),
('4', 3, 'What is hydropower?', '["Sun power", "Electricity from moving water", "Wind power", "Coal power"]', 1),
('4', 3, 'What is a hydroelectric dam?', '["Bridge", "Structure that generates power from water flow", "Water storage only", "Decoration"]', 1),
('4', 3, 'What is run-of-river hydro?', '["Lake power", "Generating power without large reservoir", "Dam power", "Ocean power"]', 1),
('4', 3, 'What is pumped-storage hydropower?', '["Drinking water", "Energy storage by pumping water uphill", "River flow", "Dam building"]', 1),
('4', 3, 'What is geothermal energy?', '["Solar heat", "Heat from within the Earth", "Wind heat", "Fire"]', 1),
('4', 3, 'What is biomass energy?', '["Rock power", "Energy from organic materials", "Wind power", "Water power"]', 1),
('4', 3, 'What is tidal energy?', '["Sun power", "Power from ocean tides", "Wind power", "Fossil fuel"]', 1),
('4', 3, 'What is wave energy?', '["Sound power", "Power from ocean waves", "Radio waves", "Light waves"]', 1),
('4', 3, 'Where is geothermal most viable?', '["Anywhere", "Areas with volcanic or tectonic activity", "Polar regions", "Deserts"]', 1),
('4', 3, 'What is the oldest renewable energy source?', '["Solar panels", "Hydropower", "Wind turbines", "Nuclear"]', 1),
('4', 4, 'Why is energy storage important for renewables?', '["Not important", "Stores power when generation exceeds demand", "Makes it expensive", "No reason"]', 1),
('4', 4, 'What is a battery energy storage system?', '["Generator", "Large batteries storing electrical energy", "Solar panel", "Wire"]', 1),
('4', 4, 'What type of battery is common for storage?', '["AA battery", "Lithium-ion", "Lead pencil", "No batteries"]', 1),
('4', 4, 'What is pumped hydro storage?', '["Well water", "Storing energy by pumping water uphill", "River dam", "Rain collection"]', 1),
('4', 4, 'What is the electrical grid?', '["Internet", "Network delivering electricity", "Solar panel", "Battery"]', 1),
('4', 4, 'What is a smart grid?', '["Dumb grid", "Grid using digital tech to manage supply and demand", "Old grid", "No grid"]', 1),
('4', 4, 'What is grid stability?', '["Grid size", "Maintaining consistent power frequency and voltage", "Grid age", "Wire length"]', 1),
('4', 4, 'What is demand response?', '["Power outage", "Adjusting consumption based on supply", "Fixed usage", "No response"]', 1),
('4', 4, 'What is distributed generation?', '["Central plant", "Small-scale power generation at point of use", "Large utility", "No power"]', 1),
('4', 4, 'What is energy arbitrage?', '["Theft", "Storing cheap energy to use when expensive", "Wasting energy", "No storage"]', 1),
('4', 5, 'What is the trend in renewable energy costs?', '["Increasing", "Decreasing rapidly", "Staying same", "Unpredictable"]', 1),
('4', 5, 'What is green hydrogen?', '["Green paint", "Hydrogen produced using renewable energy", "Natural gas", "Oil"]', 1),
('4', 5, 'What is a microgrid?', '["Tiny battery", "Localized energy grid that can operate independently", "Large utility", "Solar panel"]', 1),
('4', 5, 'What is carbon capture?', '["Carbon release", "Technology to capture CO2 emissions", "Tree planting", "Coal mining"]', 1),
('4', 5, 'What is electrification?', '["Electric shock", "Replacing fossil fuels with electricity", "Building power plants", "Grid expansion"]', 1),
('4', 5, 'What are perovskite solar cells?', '["Old technology", "Next-gen high-efficiency solar material", "Battery type", "Wind turbine"]', 1),
('4', 5, 'What is floating solar?', '["Underwater panels", "Solar panels on water bodies", "Flying panels", "Space panels"]', 1),
('4', 5, 'What is the circular economy?', '["Round buildings", "System that minimizes waste and reuses resources", "Recycling only", "Shopping"]', 1),
('4', 5, 'What policy supports renewable energy?', '["None", "Feed-in tariffs and renewable portfolio standards", "Fossil fuel subsidies", "No policies"]', 1),
('4', 5, 'What is energy democracy?', '["Voting", "Community ownership and control of energy", "Corporate control", "Government monopoly"]', 1);