-- Course 3: Water Conservation Methods (6 modules, 10 questions each)
INSERT INTO module_test_questions (course_id, module_id, question, options, correct_answer) VALUES
('3', 0, 'Why is water conservation important?', '["It is not", "Water is a limited resource essential for life", "To save money only", "For fun"]', 1),
('3', 0, 'What percentage of Earth water is freshwater?', '["50%", "About 2.5%", "90%", "All of it"]', 1),
('3', 0, 'What is water scarcity?', '["Too much water", "Insufficient water to meet demands", "Clean water", "Ocean water"]', 1),
('3', 0, 'What sector uses the most water globally?', '["Residential", "Agriculture", "Industry", "Recreation"]', 1),
('3', 0, 'What is virtual water?', '["Digital water", "Water used to produce goods and services", "Rainwater", "Bottled water"]', 1),
('3', 0, 'What is a water footprint?', '["Puddle size", "Total water used directly and indirectly", "Shoe print", "Pool size"]', 1),
('3', 0, 'What causes water stress?', '["Rain", "Demand exceeding available supply", "Conservation", "Recycling"]', 1),
('3', 0, 'What is sustainable water use?', '["Using all water", "Using water without depleting future supply", "Wasting water", "Buying water"]', 1),
('3', 0, 'What is grey water?', '["Dirty water", "Used water from sinks, showers, and laundry", "Ocean water", "Rainwater"]', 1),
('3', 0, 'What is the water cycle?', '["Water wheel", "Continuous movement of water on Earth", "Bike race", "Water bottle"]', 1),
('3', 1, 'What is the easiest way to save water at home?', '["Use more", "Fix leaks and use efficient fixtures", "Build a pool", "Water lawn more"]', 1),
('3', 1, 'How much water can a leaky faucet waste?', '["None", "Up to 3,000 gallons per year", "One drop", "Only a little"]', 1),
('3', 1, 'What is a low-flow showerhead?', '["Broken shower", "Fixture that reduces water flow while showering", "High-pressure shower", "Decoration"]', 1),
('3', 1, 'How can you save water while brushing teeth?', '["Use hot water", "Turn off tap while brushing", "Keep water running", "Brush longer"]', 1),
('3', 1, 'What is a dual-flush toilet?', '["Broken toilet", "Toilet with two flush options for different waste types", "Toilet that flushes twice", "Expensive toilet"]', 1),
('3', 1, 'How much water does a full bathtub use?', '["5 gallons", "30-50 gallons", "100 gallons", "1 gallon"]', 1),
('3', 1, 'What is more water-efficient: shower or bath?', '["Bath", "Short shower (under 5 minutes)", "Both same", "Neither"]', 1),
('3', 1, 'How can you reduce dishwashing water use?', '["Wash one item at a time", "Run full loads in dishwasher", "Use hot water only", "Pre-rinse everything"]', 1),
('3', 1, 'What is an aerator?', '["Water heater", "Device that mixes air with water to reduce flow", "Filter", "Valve"]', 1),
('3', 1, 'How often should you check for leaks?', '["Never", "Regularly, at least once a month", "Every 10 years", "Only when obvious"]', 1),
('3', 2, 'What is xeriscaping?', '["No landscaping", "Landscaping that reduces water needs", "Tropical garden", "Grass only"]', 1),
('3', 2, 'When is the best time to water plants?', '["Noon", "Early morning or evening", "Midday", "Anytime"]', 1),
('3', 2, 'What is drip irrigation?', '["Leaky hose", "Efficient watering system delivering water to roots", "Sprinkler", "Rain"]', 1),
('3', 2, 'How much water does a typical lawn need per week?', '["No water", "About 1 inch", "10 inches", "Daily watering"]', 1),
('3', 2, 'What is mulch used for in water conservation?', '["Decoration", "Retains soil moisture and reduces evaporation", "Blocks rain", "Fertilizer"]', 1),
('3', 2, 'What are native plants?', '["Foreign plants", "Plants adapted to local climate", "Indoor plants", "Weeds"]', 1),
('3', 2, 'Why choose native plants?', '["They are pretty", "They require less water and maintenance", "They are expensive", "No reason"]', 1),
('3', 2, 'What is a rain sensor?', '["Weather app", "Device that stops irrigation when it rains", "Thermometer", "Wind gauge"]', 1),
('3', 2, 'How can you water more efficiently?', '["Water daily", "Water deeply but less frequently", "Water at noon", "Use sprinklers only"]', 1),
('3', 2, 'What is a rain barrel?', '["Decoration", "Container for collecting and storing rainwater", "Trash can", "Planter"]', 1),
('3', 3, 'What is rainwater harvesting?', '["Farming in rain", "Collecting and storing rainwater for use", "Cloud seeding", "Rain dancing"]', 1),
('3', 3, 'What are the main components of a rainwater system?', '["Just a bucket", "Catchment, conveyance, storage, and distribution", "Roof only", "Pump only"]', 1),
('3', 3, 'What surface is best for collecting rainwater?', '["Dirt", "Metal or tile roof", "Asphalt", "Grass"]', 1),
('3', 3, 'What is a first flush diverter?', '["Water heater", "Device that diverts initial dirty runoff", "Pump", "Filter"]', 1),
('3', 3, 'How should rainwater be filtered?', '["It should not be", "Using screens and filters to remove debris", "With chemicals", "By boiling"]', 1),
('3', 3, 'Can harvested rainwater be used for drinking?', '["Always safe", "Only with proper treatment and filtration", "Never", "Without testing"]', 1),
('3', 3, 'What size storage tank do you need?', '["Biggest possible", "Based on rainfall, roof area, and usage", "Small bucket", "No storage needed"]', 1),
('3', 3, 'What is a common use for harvested rainwater?', '["Drinking without treatment", "Irrigation and toilet flushing", "Swimming", "Cooking"]', 1),
('3', 3, 'How do you prevent mosquito breeding in tanks?', '["Leave open", "Screen all openings and seal tank", "Add fish", "Empty daily"]', 1),
('3', 3, 'What maintenance does a rainwater system need?', '["None", "Regular cleaning of gutters, filters, and tanks", "Only repairs", "Annual inspection"]', 1),
('3', 4, 'What is greywater?', '["Dirty water", "Used water from sinks, showers, and laundry", "Drinking water", "Sewage"]', 1),
('3', 4, 'Can greywater be used for irrigation?', '["Never", "Yes, with proper treatment", "Always without treatment", "Only in summer"]', 1),
('3', 4, 'What water should NOT be used as greywater?', '["Shower water", "Toilet water (blackwater)", "Sink water", "Laundry water"]', 1),
('3', 4, 'What is a greywater treatment system?', '["Just a pipe", "System that filters and treats greywater for reuse", "Storage tank", "Pump"]', 1),
('3', 4, 'What plants can receive greywater?', '["None", "Non-edible ornamentals and trees", "Root vegetables", "Leafy greens"]', 1),
('3', 4, 'What soaps are safe for greywater?', '["All soaps", "Biodegradable, low-sodium soaps", "Bleach-based cleaners", "Any detergent"]', 1),
('3', 4, 'How should greywater be distributed?', '["Spray everywhere", "Subsurface irrigation to avoid contact", "Surface flooding", "Sprinklers"]', 1),
('3', 4, 'What is the benefit of greywater recycling?', '["None", "Reduces water use and wastewater", "More expensive", "Complicated"]', 1),
('3', 4, 'Are permits required for greywater systems?', '["Never", "Often yes, check local regulations", "Always no", "Only for large systems"]', 1),
('3', 4, 'What is a mulch basin?', '["Flower bed", "Area where greywater is dispersed and filtered by mulch", "Compost pile", "Storage tank"]', 1),
('3', 5, 'What is precision agriculture?', '["Random farming", "Using technology to optimize water use", "Old methods", "Dry farming"]', 1),
('3', 5, 'What is drip irrigation benefit in agriculture?', '["Wastes water", "Delivers water directly to roots efficiently", "Floods field", "Expensive"]', 1),
('3', 5, 'What is water-use efficiency in industry?', '["Using more water", "Producing more output per unit of water", "Wasting water", "No measurement"]', 1),
('3', 5, 'What is a cooling tower?', '["Ice maker", "Device that cools water for industrial reuse", "Water heater", "Storage tank"]', 1),
('3', 5, 'How can agriculture reduce water use?', '["Flood irrigation", "Use efficient irrigation and drought-resistant crops", "Water constantly", "No change needed"]', 1),
('3', 5, 'What is soil moisture monitoring?', '["Guessing", "Measuring soil water content to optimize irrigation", "Weather forecast", "Plant growth"]', 1),
('3', 5, 'What is water recycling in industry?', '["Wasting water", "Treating and reusing water in processes", "Buying more water", "No recycling"]', 1),
('3', 5, 'What is deficit irrigation?', '["Over-watering", "Applying less water than full need to save water", "No irrigation", "Flood irrigation"]', 1),
('3', 5, 'Why is water auditing important?', '["It is not", "Identifies water waste and improvement opportunities", "For records only", "Expensive"]', 1),
('3', 5, 'What technology helps monitor water use?', '["None", "Smart sensors and meters", "Calendars", "Guessing"]', 1);