-- Course 5: Waste Management & Recycling (6 modules, 10 questions each)
-- Course 6: Energy Efficiency Auditing (6 modules, 10 questions each)
INSERT INTO module_test_questions (course_id, module_id, question, options, correct_answer) VALUES
('5', 0, 'What is waste management?', '["Creating waste", "Collection, transport, and disposal of waste", "Littering", "Shopping"]', 1),
('5', 0, 'What is municipal solid waste?', '["Industrial waste", "Everyday trash from homes and businesses", "Medical waste", "Hazardous waste"]', 1),
('5', 0, 'What are the 3 Rs?', '["Run, Rest, Relax", "Reduce, Reuse, Recycle", "Read, Write, Review", "Red, Round, Real"]', 1),
('5', 0, 'What is the waste hierarchy?', '["Waste size", "Priority order for waste management", "Waste weight", "Trash can"]', 1),
('5', 0, 'What is the most preferred waste management option?', '["Landfill", "Waste prevention", "Incineration", "Recycling"]', 1),
('5', 0, 'What is a landfill?', '["Park", "Site for waste disposal by burial", "Recycling center", "Store"]', 1),
('5', 0, 'What is leachate?', '["Clean water", "Contaminated liquid from landfill", "Fertilizer", "Recycled material"]', 1),
('5', 0, 'What percentage of waste can typically be recycled?', '["0%", "50-75%", "100%", "5%"]', 1),
('5', 0, 'What is e-waste?', '["Email", "Discarded electronic devices", "Energy waste", "Food waste"]', 1),
('5', 0, 'Why is waste management important?', '["It is not", "Protects health and environment", "Creates jobs only", "No reason"]', 1),
('5', 1, 'What is recycling?', '["Making trash", "Converting waste into reusable material", "Burning waste", "Burying waste"]', 1),
('5', 1, 'What materials are commonly recyclable?', '["Only plastic", "Paper, glass, metal, and some plastics", "Food waste", "Diapers"]', 1),
('5', 1, 'What is single-stream recycling?', '["One item only", "All recyclables mixed in one bin", "Separate sorting", "No recycling"]', 1),
('5', 1, 'What is contamination in recycling?', '["Clean materials", "Non-recyclables mixed with recyclables", "Sorted waste", "New items"]', 1),
('5', 1, 'Can pizza boxes be recycled?', '["Always", "Only if not greasy", "Never", "After washing"]', 1),
('5', 1, 'What is downcycling?', '["Upgrading", "Recycling into lower-quality material", "Not recycling", "Composting"]', 1),
('5', 1, 'What is closed-loop recycling?', '["Throwing away", "Material recycled into same product repeatedly", "One-time recycle", "No recycling"]', 1),
('5', 1, 'What plastic number is most recyclable?', '["All equally", "#1 (PET) and #2 (HDPE)", "#7", "None"]', 1),
('5', 1, 'Should you rinse recyclables?', '["Never", "Yes, to prevent contamination", "Only sometimes", "Use soap"]', 1),
('5', 1, 'What is wishcycling?', '["Good practice", "Putting non-recyclables in recycling hoping they are", "Donating", "Composting"]', 1),
('5', 2, 'What is composting?', '["Burning", "Decomposing organic waste into soil amendment", "Recycling plastic", "Landfilling"]', 1),
('5', 2, 'What can be composted?', '["Plastic bags", "Fruit scraps, vegetables, and yard waste", "Metal cans", "Glass"]', 1),
('5', 2, 'What cannot be composted?', '["Leaves", "Meat, dairy, and pet waste", "Vegetable peels", "Coffee grounds"]', 1),
('5', 2, 'What is green material in composting?', '["Green colored items", "Nitrogen-rich materials like food scraps", "Plastic", "Glass"]', 1),
('5', 2, 'What is brown material in composting?', '["Brown colored items", "Carbon-rich materials like leaves", "Dirt", "Rocks"]', 1),
('5', 2, 'What is the ideal green-to-brown ratio?', '["All green", "About 1:2 or 1:3", "All brown", "Equal parts"]', 1),
('5', 2, 'What conditions speed up composting?', '["Cold and dry", "Warm, moist, and aerated", "Frozen", "No oxygen"]', 1),
('5', 2, 'How long does composting take?', '["One day", "2-12 months depending on method", "One week", "Years"]', 1),
('5', 2, 'What is vermicomposting?', '["Hot composting", "Using worms to break down waste", "Chemical process", "Burning"]', 1),
('5', 2, 'What is the benefit of compost?', '["None", "Enriches soil and reduces landfill waste", "Smells bad", "Creates waste"]', 1),
('5', 3, 'What is hazardous waste?', '["Normal trash", "Waste that poses danger to health or environment", "Paper", "Food waste"]', 1),
('5', 3, 'What are examples of household hazardous waste?', '["Newspaper", "Paint, batteries, and cleaning chemicals", "Cardboard", "Food scraps"]', 1),
('5', 3, 'How should batteries be disposed of?', '["Regular trash", "At designated collection points", "Burn them", "In recycling bin"]', 1),
('5', 3, 'What is e-waste?', '["Email", "Electronic waste like old phones and computers", "Energy waste", "Food waste"]', 1),
('5', 3, 'Why is e-waste dangerous?', '["It is not", "Contains toxic materials like lead and mercury", "Too heavy", "Takes space"]', 1),
('5', 3, 'How should paint be disposed of?', '["Pour down drain", "Dry out or take to hazardous waste facility", "Regular trash", "Burn it"]', 1),
('5', 3, 'What is the symbol for hazardous waste?', '["Smiley face", "Skull and crossbones or warning triangle", "Heart", "Star"]', 1),
('5', 3, 'Can fluorescent bulbs go in regular trash?', '["Yes", "No, they contain mercury", "Sometimes", "After breaking"]', 1),
('5', 3, 'What is a household hazardous waste collection event?', '["Party", "Event where residents can safely dispose of hazardous items", "Sale", "Festival"]', 1),
('5', 3, 'Why read product labels?', '["Not necessary", "To find disposal instructions", "For fun", "To check price"]', 1),
('5', 4, 'What is source reduction?', '["Recycling", "Reducing waste at the point of creation", "Burning", "Burying"]', 1),
('5', 4, 'What is a reusable alternative to plastic bags?', '["More plastic bags", "Cloth or canvas bags", "Paper plates", "Styrofoam"]', 1),
('5', 4, 'What is zero waste?', '["Recycling only", "Lifestyle aimed at sending nothing to landfill", "Creating waste", "Burning everything"]', 1),
('5', 4, 'How can you reduce food waste?', '["Buy more", "Plan meals and store food properly", "Throw away more", "Never shop"]', 1),
('5', 4, 'What is planned obsolescence?', '["Long-lasting products", "Designing products to fail or become outdated", "Quality manufacturing", "Repairable items"]', 1),
('5', 4, 'What is buying in bulk beneficial?', '["More expensive", "Reduces packaging waste", "Creates waste", "Harder to store"]', 1),
('5', 4, 'What is upcycling?', '["Throwing away", "Creating higher-value products from waste", "Burning", "Burying"]', 1),
('5', 4, 'What is a circular economy?', '["Linear consumption", "System that eliminates waste through reuse", "One-time use", "Wasteful economy"]', 1),
('5', 4, 'What is minimalism?', '["Hoarding", "Lifestyle of owning fewer possessions", "Shopping more", "Wasting"]', 1),
('5', 4, 'What is the best way to reduce waste?', '["Recycle everything", "Not create it in the first place", "Burn it", "Hide it"]', 1),
('5', 5, 'What is industrial waste?', '["Home trash", "Waste from manufacturing and industry", "Food waste", "Paper"]', 1),
('5', 5, 'What is construction and demolition waste?', '["Office paper", "Debris from building projects", "Food", "Electronics"]', 1),
('5', 5, 'What percentage of C&D waste can be recycled?', '["0%", "Up to 70-90%", "5%", "100%"]', 1),
('5', 5, 'What is an environmental management system?', '["Trash can", "Framework for managing environmental responsibilities", "Recycling bin", "Landfill"]', 1),
('5', 5, 'What is waste auditing?', '["Guessing", "Analyzing waste streams to identify reduction opportunities", "Throwing away", "Ignoring"]', 1),
('5', 5, 'What is extended producer responsibility?', '["Consumer duty", "Manufacturers responsible for end-of-life product management", "Government role", "No responsibility"]', 1),
('5', 5, 'What is industrial symbiosis?', '["Competition", "One industry using another waste as resource", "Isolation", "No cooperation"]', 1),
('5', 5, 'What is the cradle-to-cradle concept?', '["Linear use", "Designing products for continuous reuse", "One-time use", "Disposal focus"]', 1),
('5', 5, 'What is life-cycle assessment?', '["Age check", "Analyzing environmental impact from production to disposal", "Price evaluation", "Color analysis"]', 1),
('5', 5, 'Why is waste-to-energy controversial?', '["It is not", "May discourage recycling and create emissions", "Too efficient", "Free energy"]', 1),
('6', 0, 'What is an energy audit?', '["Electricity bill", "Assessment of energy use to identify savings", "Power outage", "Installation"]', 1),
('6', 0, 'What are the types of energy audits?', '["Only one type", "Walk-through, standard, and detailed", "Expensive only", "No types"]', 1),
('6', 0, 'What is energy efficiency?', '["Using more energy", "Using less energy to accomplish same task", "Wasting energy", "No energy"]', 1),
('6', 0, 'What is the benefit of energy auditing?', '["Higher bills", "Identifies cost-saving opportunities", "No benefits", "More consumption"]', 1),
('6', 0, 'Who performs energy audits?', '["Anyone", "Certified energy auditors", "Only homeowners", "No one"]', 1),
('6', 0, 'What is a walk-through audit?', '["Exercise", "Quick visual inspection", "Detailed analysis", "No inspection"]', 1),
('6', 0, 'What tools are used in energy audits?', '["None", "Thermal cameras, blower doors, and meters", "Hammer", "Pen only"]', 1),
('6', 0, 'What is energy baseline?', '["Starting point", "Current energy consumption benchmark", "Goal", "No measurement"]', 1),
('6', 0, 'What is return on investment (ROI)?', '["Loss", "Financial return from efficiency improvements", "Cost only", "No return"]', 1),
('6', 0, 'Why is building envelope important?', '["It is not", "It controls heat transfer and energy loss", "For looks", "Mailing"]', 1),
('6', 1, 'What is the largest energy user in homes?', '["Lights", "Heating and cooling", "TV", "Toaster"]', 1),
('6', 1, 'What is a blower door test?', '["Fan", "Test measuring home air leakage", "Door installation", "Wind test"]', 1),
('6', 1, 'What is thermal imaging?', '["Photography", "Using infrared to detect heat loss", "X-ray", "Light measurement"]', 1),
('6', 1, 'What is an R-value?', '["Room size", "Insulation thermal resistance", "Wall color", "Window size"]', 1),
('6', 1, 'Where is most heat lost in homes?', '["Walls", "Windows, doors, and attics", "Floors", "Nowhere"]', 1),
('6', 1, 'What is air sealing?', '["Removing air", "Closing gaps to prevent air leakage", "Opening windows", "Ventilation"]', 1),
('6', 1, 'What is a home energy rating?', '["House price", "Score indicating energy efficiency", "Size rating", "Color code"]', 1),
('6', 1, 'What are vampire loads?', '["Horror movies", "Power used by devices when off", "High power use", "Batteries"]', 1),
('6', 1, 'What is programmable thermostat benefit?', '["More expensive", "Automatically adjusts temperature for savings", "No benefit", "Decoration"]', 1),
('6', 1, 'What is the payback period?', '["Interest", "Time to recover investment through savings", "Loan term", "No return"]', 1),
('6', 2, 'What differs in commercial energy audits?', '["Nothing", "Larger scale and complex systems", "Easier", "No difference"]', 1),
('6', 2, 'What is an energy management system?', '["Light switch", "Automated system controlling building energy", "Generator", "Battery"]', 1),
('6', 2, 'What is demand charge?', '["Monthly fee", "Cost based on peak power use", "Energy cost", "No charge"]', 1),
('6', 2, 'What is load factor?', '["Weight", "Ratio of average to peak demand", "Building size", "Efficiency"]', 1),
('6', 2, 'What are the largest energy consumers in industry?', '["Lights", "Motors, heating, and process equipment", "Computers", "Signs"]', 1),
('6', 2, 'What is power quality?', '["Quantity", "Consistency of voltage and frequency", "Brand", "Color"]', 1),
('6', 2, 'What is cogeneration?', '["Two generators", "Simultaneous production of electricity and heat", "Backup power", "Solar power"]', 1),
('6', 2, 'What is variable frequency drive (VFD)?', '["Music system", "Device controlling motor speed for efficiency", "Power supply", "Light"]', 1),
('6', 2, 'What is compressed air efficiency?', '["Size", "Minimizing leaks and optimizing system", "Pressure", "Volume"]', 1),
('6', 2, 'What is energy benchmarking?', '["Guessing", "Comparing energy use to similar buildings", "Random data", "No comparison"]', 1),
('6', 3, 'What does HVAC stand for?', '["High Voltage AC", "Heating, Ventilation, and Air Conditioning", "Heavy Vehicle", "Home Value"]', 1),
('6', 3, 'What is SEER rating?', '["Sight test", "Seasonal Energy Efficiency Ratio", "Size rating", "Sound level"]', 1),
('6', 3, 'What SEER rating is considered efficient?', '["5", "14 or higher", "1", "100"]', 1),
('6', 3, 'What is a heat pump?', '["Heater only", "Device that heats and cools", "Water pump", "Fan"]', 1),
('6', 3, 'What is duct leakage?', '["Water leak", "Air escaping from ductwork", "Sound", "Light"]', 1),
('6', 3, 'How much energy can duct sealing save?', '["Nothing", "Up to 20%", "1%", "200%"]', 1),
('6', 3, 'What is zoning in HVAC?', '["Area code", "Controlling temperature in different areas independently", "Single temp", "No control"]', 1),
('6', 3, 'What is economizer mode?', '["Cheap system", "Using outside air for cooling when possible", "No cooling", "Expensive mode"]', 1),
('6', 3, 'How often should HVAC filters be changed?', '["Never", "Every 1-3 months", "Every 10 years", "Daily"]', 1),
('6', 3, 'What is the ideal temperature for savings?', '["80°F in winter", "68°F in winter, 78°F in summer", "Same year-round", "No control"]', 1),
('6', 4, 'What is the most efficient lighting?', '["Incandescent", "LED", "Candles", "Oil lamps"]', 1),
('6', 4, 'How much more efficient are LEDs than incandescent?', '["Same", "75-80% more efficient", "10%", "Twice"]', 1),
('6', 4, 'What is lumens?', '["Wattage", "Measure of light output", "Bulb size", "Color"]', 1),
('6', 4, 'What is color temperature in lighting?', '["Physical heat", "Appearance of light from warm to cool", "Brightness", "Efficiency"]', 1),
('6', 4, 'What are occupancy sensors?', '["Security", "Switches that turn lights on/off based on presence", "Motion alarm", "Cameras"]', 1),
('6', 4, 'What is daylighting?', '["Daylight Saving Time", "Using natural light to reduce electric lighting", "Morning work", "Window cleaning"]', 1),
('6', 4, 'What is a ballast?', '["Weight", "Device regulating current to fluorescent lights", "Light bulb", "Switch"]', 1),
('6', 4, 'What is power factor?', '["Strength", "Ratio of real to apparent power", "Voltage", "Wattage"]', 1),
('6', 4, 'What is the purpose of lighting controls?', '["Decoration", "Optimizing when and how much light is used", "No purpose", "Security only"]', 1),
('6', 4, 'What is task lighting?', '["Work schedule", "Focused light for specific activities", "General light", "Emergency light"]', 1),
('6', 5, 'What is the audit report?', '["Bill", "Document detailing findings and recommendations", "Advertisement", "Receipt"]', 1),
('6', 5, 'How are recommendations prioritized?', '["Randomly", "By cost-effectiveness and ROI", "Alphabetically", "No priority"]', 1),
('6', 5, 'What is a no-cost measure?', '["Free equipment", "Behavioral changes requiring no investment", "Expensive upgrade", "New system"]', 1),
('6', 5, 'What is low-hanging fruit?', '["Apple tree", "Easy, cost-effective improvements", "Difficult tasks", "No improvements"]', 1),
('6', 5, 'What is lifecycle cost?', '["Purchase price only", "Total cost over product lifetime", "Installation cost", "Monthly bill"]', 1),
('6', 5, 'What are energy incentives?', '["Penalties", "Rebates or tax credits for efficiency improvements", "Fines", "No benefits"]', 1),
('6', 5, 'What is measurement and verification (M&V)?', '["Guessing", "Confirming actual energy savings", "Installation", "Audit"]', 1),
('6', 5, 'What is commissioning?', '["Payment", "Ensuring systems operate as intended", "Purchase", "Delivery"]', 1),
('6', 5, 'What is continuous improvement?', '["One-time fix", "Ongoing process of finding and implementing savings", "No changes", "Random changes"]', 1),
('6', 5, 'What is the first step after audit?', '["Nothing", "Implementing high-priority recommendations", "Forget it", "Wait"]', 1);